# Site settings
title: ddd's Blog
email: 542377628@qq.com
description: > # this means to ignore newlines until "baseurl:"
  My personal Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jiangroubao.cn" # the base hostname & protocol for your site
twitter_username: none
github_username:  kkj154393476

# Build settings
markdown: kramdown
